environment_variables: {}
external_package_dirs: []
model_metadata:
  avatar_url: https://cdn.baseten.co/production/static/explore/meta.png
  cover_image_url: https://cdn.baseten.co/production/static/explore/llama.png
  repo_id: meta-llama/Meta-Llama-3-8B-Instruct
  tags:
  - text-generation
model_name: Ultravox 0.2
python_version: py311
model_cache:
  - repo_id: fixie-ai/ultravox-v0.2
requirements: []
requirements_file: ./requirements.txt
resources:
  accelerator: A100
  use_gpu: true
secrets:
  hf_access_token: "your-hf-access-token"
system_packages: []
